f = 100; %sila pusobici na vozik
M = 50; %hmostnost voziku
m = 10; %hmotnost tělesa na lane
dx = 0; %pocatecni rychlost voziku
x = 0; %pocatecni poloh voziku
dphi = 0; %pocatecni rychlost kyvadla
phi = 20; %pocatecni poloha kyvadla
l = 1; %delka zavesu
g = 9.81; %gravitacni sila
